In [4]:
import numpy as np

def sigmoid(x):
    """
    Calculate sigmoid
    """
    return 1/(1+np.exp(-x))

# Network size
N_input = 4
N_hidden = 3
N_output = 2

np.random.seed(42)
# Make some fake data
X = np.random.randn(4)

weights_input_to_hidden = np.random.normal(0, scale=0.1, size=(N_input, N_hidden))
weights_hidden_to_output = np.random.normal(0, scale=0.1, size=(N_hidden, N_output))

In [13]:
# array with len of 4
X.shape

(4,)

In [45]:
# minimized to 2 for simplicity
X[:2]

array([ 0.49671415, -0.1382643 ])

In [15]:
# array with 4 rows and 3 columns
weights_input_to_hidden.shape

(4, 3)

In [46]:
# minimized to 2 rows of 3 columns for simplicity
weights_input_to_hidden[:2]

array([[-0.02341534, -0.0234137 ,  0.15792128],
       [ 0.07674347, -0.04694744,  0.054256  ]])

In [47]:
# numpy calculation of vector and matrix
np.dot(X[:2], weights_input_to_hidden[:2])

array([-0.02224161, -0.00513876,  0.07094007])

In [48]:
# practical example of vector to matrix calculations
first = 0.49671415 * -0.02341534 + -0.1382643 * 0.07674347
second = 0.49671415 * -0.0234137 +  -0.1382643 * -0.04694744
third = 0.49671415 * 0.15792128 + -0.1382643  * 0.054256

In [49]:
# results should match numpy method
print(first, second, third)

-0.022241612864181998 -0.0051387611654630004 0.070940066501312


In [51]:
# applying sigmoid function
sigmoid(np.dot(X[:2], weights_input_to_hidden[:2]))

array([0.49443983, 0.49871531, 0.51772758])

In [53]:
# array of 3 rows and 2 columns - the 3 rows matches the 3 columns previously calculated
weights_hidden_to_output

array([[-0.10128311,  0.03142473],
       [-0.09080241, -0.14123037],
       [ 0.14656488, -0.02257763]])

In [54]:
# TODO: Make a forward pass through the network

hidden_layer_in = np.dot(X, weights_input_to_hidden)
hidden_layer_out = sigmoid(hidden_layer_in)

print('Hidden-layer Output:')
print(hidden_layer_out)

output_layer_in = np.dot(hidden_layer_out, weights_hidden_to_output)
output_layer_out = sigmoid(output_layer_in)

print('Output-layer Output:')
print(output_layer_out)

Hidden-layer Output:
[0.41492192 0.42604313 0.5002434 ]
Output-layer Output:
[0.49815196 0.48539772]
